[project]
name = "segreg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anndata>=0.12.7",
    "patsy>=1.0.2",
    "spatialdata>=0.7.2",
    "torch>=2.8.0, <2.9.0",
    "torch-geometric>=2.7.0",
    "pyg-lib>=0.5.0",
    "tqdm>=4.67.1",
    "squidpy>=1.8.1",
]

[tool.uv.sources]
pyg-lib = { url = "https://data.pyg.org/whl/torch-2.8.0%2Bcu128/pyg_lib-0.5.0%2Bpt28cu128-cp313-cp313-linux_x86_64.whl" }
dapple = { path = "../dapple_py", editable = true }

[tool.pyright]
venvPath = "."
venv = ".venv"

[dependency-groups]
debug = [
    "dapple",
    "marimo>=0.20.4",
    "umap-learn>=0.5.11",
]
